### ISSUE TITLE
Peer dependency warning, outdated version on npm?

### ISSUE THREAD

**Issue by shroudedcode** [piotrwitek/ts-mocha#13]
I just installed `ts-mocha` in a fresh project folder without a dist-tag (so it should be latest version) and got this error:

```
npm WARN ts-mocha@1.0.3 requires a peer of mocha@^3.2.0 but none is installed.
You must install peer dependencies yourself.
```

This surprised me since the `package.json` in this repository (version `1.0.3`) states that both Mocha 3 and 4 (which I use) are supported as peer dependencies (`^3.X.X || ^4.X.X`). The version of `ts-mocha` that I've installed (also `1.0.3`?!) however only supports Mocha 3 (^3.2.0`), so I get this error message. Is the latest version not on npm? :confused:

**Comment by piotrwitek** [comment]
@shroudedcode Hello
Sorry but I didn't released a new version yet.
I released a new version 1.1.0 just now.
Could you please test it now and tell me if everything works as expected now?

**Comment by shroudedcode** [comment]
Yes, the warning message is gone. Thanks! :+1:

**Comment by piotrwitek** [comment]
Enjoy :)
