### ISSUE TITLE
Out-of-date mocha version

### ISSUE THREAD

**Issue by cungminh2710** [piotrwitek/ts-mocha#18]
Can you please bump up the `mocha` version in `ts-mocha` to ^5.X.X
`"ts-mocha#mocha@^3.X.X || ^4.X.X" doesn't satisfy found match of "mocha@5.0.5"`

**Comment by piotrwitek** [comment]
Hi @cungminh2710,
yes sure, shouldn't take long

**Comment by piotrwitek** [comment]
released: https://github.com/piotrwitek/ts-mocha/releases/tag/v1.2.0
