### ISSUE TITLE
How to use ts-mocha in code? (can't find any docs about this)

### ISSUE THREAD

**Issue by joelharkes** [piotrwitek/ts-mocha#2]
I used mocha in code like this:

```
const Mocha = require('mocha');
const mocha = new Mocha({ timeout: 50000 });
if (testSubject)
    mocha.addFile(`tests/integration/${testSubject}`);
```

now im trying to do the same for ts-mocha but it wont work.

I tried registering ts-node beforehand:

```
require('ts-node').register({ /* options */ });
```

but then i get errors that `describe` and `it` are no methods (of course).

Is there a way i can use ts-mocha like this?

Btw thanks for your amazing library, super happy to use it, its amazing!

**Comment by joelharkes** [comment]
For all those wondering i already figured it out, trying a few things:

Just include ts-mocha before:

```
require('ts-mocha');
const Mocha = require('mocha');
const mocha = new Mocha({ timeout: 50000 });
if (testSubject)
    mocha.addFile(`tests/integration/${testSubject}`);
```

It would be nice to add this to the documentation 😄

**Comment by piotrwitek** [comment]
Hi,
You answered yourself faster that I could respond, nice :)
It's really great it worked out that simple!

Perhaps you would like to become a first-time contributor and submit a PR with a change to the documentation?
Would be really appreciated!
