### ISSUE TITLE
Do not correspond to the line numbers on error

### ISSUE THREAD

**Issue by khusamov** [piotrwitek/ts-mocha#24]
Hello!
Why does the line number in the console not match the line number in the code?

![image](https://user-images.githubusercontent.com/4146998/42496002-728d488a-842d-11e8-9120-9a7b58cfb819.png)

But if you comment out the string ' Util.promisify(Hg.clone);`, then there is no error with the line number.

![image](https://user-images.githubusercontent.com/4146998/42496036-870ba13a-842d-11e8-9a48-5dd311abd3b5.png)

How to fix?

**Comment by khusamov** [comment]
It is not by chance due to the fact that the module `hg` does not have a file with a description of the types under the `typescript`?
Or maybe due to the fact that `hg` is written on `coffee-script`?

**Comment by khusamov** [comment]
Found the cause of the problem. It turns out the module `hg` is written to `coffeescript`. And it compiles during the execution of the script. And because of him such problems.

I compiled it. And inserted already in the compiled form. And the problem disappeared. Now all the lines match!!!

**Comment by piotrwitek** [comment]
That's interesting error.
Closing as there is nothing actionable in this issue.

**Comment by ruscon** [comment]
the same issue with typescript tests
