### ISSUE TITLE
[ERROR] Cannot find module 'typescript'

### ISSUE THREAD

**Issue by splincode** [piotrwitek/ts-mocha#29]
![image](https://user-images.githubusercontent.com/12021443/43637951-9ebf4af2-971f-11e8-9a4a-40815ab079c5.png)

**Comment by charlesbodman** [comment]
Latest version is working for me. 

Any more info ?

**Comment by xmakina** [comment]
If you came here from Google, you need to install typescript

`npm i -D typescript`
