### ISSUE TITLE
Changes  (angular)  src/environments/environment*.ts  files

### ISSUE THREAD

**Issue by appersonj** [piotrwitek/ts-mocha#30]
I have several files in  src/environments/ directory, 
such as environment.alternate.ts:
`
export const environment = {
 production: false,
  envName : "alternate",
  version: "${project.version}",
  extendedVersion: "${extended-version}"
};
`
These have template macros that are NOT intended to be expanded at compile time.

When I run: 
`npx ts-mocha -p .  'src/**/*.test.ts'`

It expands the variables (incorrectly) in the environments files, ACTUALLY MODIFYING THOSE FILES

Note : the following command does not modify the files, so I will fall back to using ts-node directly
`
 npx   mocha --require ts-node/register  'src/**/*.test.ts'
`

**Comment by piotrwitek** [comment]
Hey @appersonj,
Have you tried if the most recent version v2.0.0 if the issue still persist?
We updated to the newest ts-node so it's possible it had been fixed.

**Comment by appersonj** [comment]
I worked around it by running tsnode directly.
I'll try tsmocha again on the *next* project.

**Comment by piotrwitek** [comment]
Ok cool, so I'm closing for now as only you could confirm this issue. I will reopen when there is someone else hitting the same issue.
