### ISSUE TITLE
how can I end the process with the programmatic version

### ISSUE THREAD

**Issue by pscanlon1** [piotrwitek/ts-mocha#32]
I love this programmatic version. Thanks!

My question is, right now, i can do something like

ts-mocha -p tsconfig.json src/tests/**/*.ts --no-timeouts _--exit_

When the tests are complete. it will end the process. How would I / Can I do the same with your programmatic version?

Thanks!

**Comment by piotrwitek** [comment]
Hey,
You know it works the same as regular mocha, the only difference is
additional setup for ts-mocha in the top of the file.

So just check original mocha documentation for how to do what you need
programatically.

**Comment by pscanlon1** [comment]
ty, figured it out...

```
import * as Mocha from 'mocha';

process.env.TS_NODE_PROJECT = './tsconfig.json';
require('ts-mocha');
 
const mocha = new Mocha();
mocha.addFile(`./src/tests/**/*.ts`);
mocha.run((failures) => {
process.exitCode = failures ? -1 : 0;
console.log(`process exiting with exitcode = ${process.exitCode}`)
process.exit();
    process.on('exit', () => {
        console.log('process exiting from within ON()')
        process.exit(failures); // exit with non-zero status if there were failures
    });
});
```
