### ISSUE TITLE
Use ts-mocha with mocha-parallel-tests

### ISSUE THREAD

**Issue by tuliren** [piotrwitek/ts-mocha#41]
Is there a way to use `mocha-parallel-tests` under the hood instead of plain `mocha` when running `ts-mocha`? 

(I have searched in issues and pull requests here, and briefly Googled it, and could not find any answer.)

Thanks.

**Comment by piotrwitek** [comment]
Hey,
It seems to me it's a separate package that is using mocha internally so I don't see any simple way to support it other than extending mocha-parallel-tests to accept custom mocha binary through a configuration option.

**Comment by tuliren** [comment]
Got it, makes sense. I will try that. Thank you.
