### ISSUE TITLE
Warning during `yarn install` when using mocha 7

### ISSUE THREAD

**Issue by kaiyoma** [piotrwitek/ts-mocha#48]
ts-mocha needs to update its dependencies to allow mocha 7 (assuming that the two versions work together). Currently, this warning appears during installation:

```
warning " > ts-mocha@6.0.0" has incorrect peer dependency "mocha@^3.X.X || ^4.X.X || ^5.X.X || ^6.X.X".
```

**Comment by piotrwitek** [comment]
PR's welcome, it's really easy change.
