### ISSUE TITLE
ts-mocha v8 has not yet been released

### ISSUE THREAD

**Issue by azatoth** [piotrwitek/ts-mocha#59]
In #58 @piotrwitek stated he would prepare a release "this evening", but sadly I can't see a new release available on https://www.npmjs.com/package/ts-mocha

**Comment by piotrwitek** [comment]
Hey @azatoth, thanks for the reminder, unfortunately, it has slipped my mind. I'm waiting for my laptop to get back from the warranty service this week and I'm on a backup laptop now which is not set up correctly to do the release, I'll try to get back to it EOW.

If not please ping me again! Thanks!

**Comment by SQReder** [comment]
bump for this one 😉

**Comment by piotrwitek** [comment]
Thanks! My laptop is back from service. I'm on it!

**Comment by piotrwitek** [comment]
Deployed as `ts-mocha@8.0.0`
