### ISSUE TITLE
ts-mocha v9 beta released

### ISSUE THREAD

**Issue by piotrwitek** [piotrwitek/ts-mocha#61]
Hey,

I have published the next release of ts-mocha, you can try it using `npm i ts-mocha@next`

I have updated `ts-node` to the most recent v9 release.

Tests are passing so it should work as before, but please let me know if there are any issues.

**Comment by gakonst** [comment]
Hey @piotrwitek, is there any plan to release v9?

**Comment by teolag** [comment]
And any plans to support mocha 9?
`npm WARN ts-mocha@9.0.0-alpha1 requires a peer of mocha@^3.X.X || ^4.X.X || ^5.X.X || ^6.X.X || ^7.X.X || ^8.X.X but none is installed. You must install peer dependencies yourself.`

**Comment by ssipos90** [comment]
@teolag you just missed the point of this whole issue.
use `npm i -D ts-mocha@next`

**Comment by piotrwitek** [comment]
v9 is released
