### ISSUE TITLE
Option '-r' not supported.

### ISSUE THREAD

**Issue by eddow** [piotrwitek/ts-mocha#63]
I am trying to have the base case running and fail at it.

Using this command line : `ts-mocha --paths -p src/server/tsconfig.mocha.json src/server/**/*.test.ts`

Using the tsconfig c/p-ed from [here](https://github.com/piotrwitek/ts-mocha/blob/master/test/paths/tsconfig.json) (extending it manually, so without `"extends": "../tsconfig.base.json"`)

Without any `mocha.conf`, `.mocharc.js` nor entry in `package.json`

Once using the `--paths` option, I end up with this error message:

```
Option '-r' not supported. Trigger '[...]\node_modules\mocha\bin\mocha -h' for more details
```

EDIT: Afterward, I managed to have this error with `mocha -r ts-node/register`, so it's not `ts-mocha`-related. I let it opened in case somebody has an idea though

**Comment by piotrwitek** [comment]
No STR
