### ISSUE TITLE
Support mocha 9

### ISSUE THREAD

**Issue by aabmass** [piotrwitek/ts-mocha#65]
And any plans to support mocha 9?
`npm WARN ts-mocha@9.0.0-alpha1 requires a peer of mocha@^3.X.X || ^4.X.X || ^5.X.X || ^6.X.X || ^7.X.X || ^8.X.X but none is installed. You must install peer dependencies yourself.`

_Originally posted by @teolag in https://github.com/piotrwitek/ts-mocha/issues/61#issuecomment-862343195_

**Comment by beenotung** [comment]
My guess is ts-mocha is not affected by the breaking changes introduced in mocha@9.

Can we include `|| ^9.X.X` in the peer dependency list of ts-mocha?

https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes

**Comment by juergba** [comment]
> mocha@9 became an ESM module.

This is incorrect, Mocha still is a CommonJS module.

**Comment by piotrwitek** [comment]
Released a new version of ts-mocha@9, please test.
