### ISSUE TITLE
ts-node as peerDependency

### ISSUE THREAD

**Issue by connorjclark** [piotrwitek/ts-mocha#71]
My project already is using ts-node (v10), but this package brings it's own (v7). Perhaps it'd be possible to set ts-node as a peer dep and defer to the user to bring in a specific version?

**Comment by piotrwitek** [comment]
not possible because of breaking changes. What's the root issue? Normally you can have different versions of the same package in the project without problem.

**Comment by connorjclark** [comment]
I don't recall specifically but I am leaning on some newer feature in the latest ts-node, so having tests run with something different is a cause for concern. (I'm one of those people using ts-node in production too 😆 )

Closing since infeasible.
