### ISSUE TITLE
How to run parallel tests using ts-mocha

### ISSUE THREAD

**Issue by shivang16** [piotrwitek/ts-mocha#79]
How do we run the tests in parallel using ts-mocha? 
In mocha `--parallel` and `--jobs` flags help in running it. But I've tried it with ts-mocha and it's not working.

**Comment by tavy121** [comment]
Hi,
I find this feature very useful for a big set of tests.
Do you think you can implement it?

**Comment by piotrwitek** [comment]
Need your config, error + stack trace to investigate. But first, you should check if that works with mocha and ts-node, because that's what this framework is doing behind the scenes.

**Comment by shivang16** [comment]
Hi, 
If we use ts-mocha version >=8 then providing `--parallel `and `--job=job_count` flags can enable parallel tests (in the same way it is done for mocha). 

I was initially using ts-mocha version<8 and due to this I could not run my tests in parallel (since in Mocha parallel tests are supported for mocha version>=8 and ts-mocha version>=8 uses mocha version>=8). 

Refer this for more details: https://mochajs.org/#parallel-tests
